# Generated by Django 5.0.2 on 2024-04-14 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='balance',
        ),
    ]
