# Generated by Django 5.0.4 on 2024-04-14 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_question_point_mark_alter_rating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_ans',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_four',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_one',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_three',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_two',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
            ],
        ),
    ]
